version: 2
jobs:
  build:
    docker:
      - image: josler/intercom-go:1.9.4

    working_directory: /go/src/github.com/intercom/intercom-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v
      - run: go test -v ./...
